### ISSUE TITLE
run with windows 11: Chunky failed to start

### ISSUE THREAD

**Issue by AndreDriesel** [chunky-dev/chunky#1070]
I tried to start chunky on windows 11.

I started the terminal (with administration rights) and done this
`java --module-path "C:\Program Files\Java\javafx-sdk-17.0.1\lib" --add-modules javafx.controls,javafx.fxml -jar "C:\Program Files\Chunky\ChunkyLauncher.jar"`

Than the launcher starts, i updated to the current version and want to launch Chunky, but i got this error:
`Chunky failed to start!
The following command was used to start chunky:
C:\Program Files\Java\jdk-17.0.1\bin\java.exe -Xmx6120m -Dchunky.home=C:\Users\André\.chunky -Dprism.order=sw -classpath C:\Users\André\.chunky\lib\chunky-core-2.4.1.jar;C:\Users\André\.chunky\lib\commons-math3-3.2.jar;C:\Users\André\.chunky\lib\fastutil-8.4.4.jar se.llbit.chunky.main.Chunky`

The console logs this:

> Unchecked exception caused Chunky to close.
java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:224)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more
Chunky exited abnormally with exit value 2

**Comment by jackjt8** [comment]
Please ensure the `Java Options` field in the Laucher has `--module-path "C:\Program Files\Java\javafx-sdk-17.0.1\lib" --add-modules javafx.controls,javafx.fxml`.

If ChunkyLauncher auto detects JavaFX it typically autopopulates this field.. manually feeding it JavaFX might not autopopulate the field. I'll test and update the docs.

**Comment by AndreDriesel** [comment]
With these options, Chunky starts.

But there is just one problem:
To launch chunky i always need to start it with the terminal and the following command:
`java --module-path "C:\Program Files\Java\javafx-sdk-17.0.1\lib" --add-modules javafx.controls,javafx.fxml -jar ChunkyLauncher.jar`

In my installed directory \username\.chunky are just following folders:
lib, versions and 2 json files.

The chunkylauncher.jar is still in program files\chunky

**Comment by jackjt8** [comment]
If the OpenJFX directory was named and setup as the installation guide outlined you would (probably) not need to use the command line to launch Chunky. That being said we are trying to get a new installer that bundles JRE+JFX and just gives you a nice .exe to run.

In the mean time, open Notepad, paste the command you have in the file and the Save As a `.bat` file next to ChunkyLauncher.jar.

You can freely double click or make a shortcut of this `.bat` file.

You can relocate ChunkyLauncher.jar and the .bat file to another directory but maybe not within `.chunky`... hasn't really been tested so it might work?

**Comment by leMaik** [comment]
Closing due to lack of response. Feel free to reopen if you still can't launch Chunky or reach out to us on Discord. :upside_down_face:
