### ISSUE TITLE
Chunky Launcher Not Running

### ISSUE THREAD

**Issue by guitaristtom** [chunky-dev/chunky#1092]
I have JavaFX installed both system-wide as well as locally in the folder that ChunkyLauncher.jar is in.

```
[~/Downloads/chunky]$ ls
total 184K
drwxr-xr-x 3 thomas thomas 4.0K Dec 12 14:50 .
drwxr-xr-x 8 thomas thomas  12K Dec 12 14:50 ..
-rw-r--r-- 1 thomas thomas 162K Dec 12 14:41 ChunkyLauncher.jar
drwxr-xr-x 4 thomas thomas 4.0K Oct 16 11:21 javafx-sdk-17.0.1
```

However, if I try running just the ChunkyLauncher I get this error:
```
[~/Downloads/chunky]$ java -jar ChunkyLauncher.jar
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/Stage
	at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:316)
	at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:224)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Stage
	... 2 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```

Also, if I try running it with the specified commands in the documentation, I get this:
```
[~/Downloads/chunky]$ java --module-path javafx-sdk-17.0.1/lib --add-modules javafx.controls,javafx.fxml -jar ChunkyLauncher.jar 
Unrecognized option: --module-path
Error: Could not create the Java Virtual Machine.
```

Weird thing is that if I don't have JavaFX installed either way, I get this:
![Screenshot from 2021-12-12 14-57-42](https://user-images.githubusercontent.com/6890628/145732997-bf219b42-85bd-4423-9d20-9b6ae05dd38a.png)

So I know it's finding JavaFX on my system since, as stated above, I don't get that error when I have it installed either system-wide or in the folder as mentioned in the documentation.

**Comment by jackjt8** [comment]
`Unrecognized option: --module-path` implies you are using Java 8. Per the instructions, those commands on only for Java 11 or later. To install OpenJFX for Java 8 try something like:

```
apt purge openjfx
apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
apt-mark hold openjfx libopenjfx-jni libopenjfx-java
```

However it is very common that OpenJFX is broken in some way if downloaded in this fashion because maintainers just break it.  It is recommended that you actually install Oracle Java 8 (which bundles JavaFX) or update to Java 11+ instead. Java 17 is the latest LTS branch.

**Comment by guitaristtom** [comment]
Thanks for the reply.However I'm not running a distro that runs apt.On top of that, I have OpenJDK 17 installed, and I have set up JavaFX as per the instructions in the documentation. On Dec. 12, 2021 15:07, Jack Peters ***@***.***> wrote:
Unrecognized option: --module-path implies you are using Java 8. Per the instructions, those commands on only for Java 11 or later. To install OpenJFX for Java 8 try something like:
apt purge openjfx
apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
apt-mark hold openjfx libopenjfx-jni libopenjfx-java

However it is very common that OpenJFX is broken in some way if downloaded in this fashion because maintainers just break it.  It is recommended that you actually install Oracle Java 8 (which bundles JavaFX) or update to Java 11+ instead. Java 17 is the latest LTS branch.

**Comment by jackjt8** [comment]
Please try `java -version` and report what you get from it.

As stated before the fact the option is unrecognized indicates the Java 8 is being used for some reason. If your Distro doesn't support apt you need to investigate alternative solutions as this was a suggestion given no indication was given as to what you are running. If `java -version` reports JDK 8 either download OpenJFX 8 via your Distro's built-in package handler, again noting that the packages may be broken in some capacity, or remove JDK 8 and make sure JDK 17 is setup correctly. Alternatively, you maybe be able to replace `java` in the command you are using with a direct path.. but I wouldn't know how that works on Linux. For Windows it's say `"C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot\bin\java.exe"`.

**Comment by guitaristtom** [comment]
Ah, looks like you're right. For some reason, my system has Java 8 as the default option.
```
[~/Downloads/chunky]$ java -version                                 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

Looking in MultiMC, I found where Java 17 is being called from. 
```
[~/Downloads/chunky]$ /usr/lib/jvm/java-17-openjdk/bin/java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12)
OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)
```

Switching to it though, I get this now:
```
[~/Downloads/chunky]$ /usr/lib/jvm/java-17-openjdk/bin/java --module-path javafx-sdk-17.0.1/lib --add-modules javafx.controls,javafx.fxml -jar ChunkyLauncher.jar
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
```

**Comment by jackjt8** [comment]
Ok, now we need to check the contents of `javafx-sdk-17.0.1/lib`. `java.lang.module.FindException: Module javafx.controls not found` is saying it can't find javafx at that location basically.

**Comment by guitaristtom** [comment]
I deleted and redownloaded the JavaFX pack, and managed to get it to "launch" finally. But now I'm getting a crash and big stack trace.

```
[~/Downloads/chunky]$ /usr/lib/jvm/java-17-openjdk/bin/java --module-path javafx-sdk-17.0.1/lib --add-modules javafx.controls,javafx.fxml -jar ChunkyLauncher.jar
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "Thread-0" java.lang.RuntimeException: No toolkit found
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jackjt8** [comment]
To troubleshoot we need you to include `-Dprism.verbose=true` in the launch options.

If it points to a missing GTK2 you'll need to grab that.

Otherwise you may have mismatched the SDK. Please double check you have the right one for your system (IE aarch64 SDK Vs x64 SDK).

**Comment by leMaik** [comment]
Closing this after 14 days without a reply. If the problem persists, re-open this issue or reach out to us on Discord or Reddit. :+1:
