### ISSUE TITLE
Chunky Won't Launch

### ISSUE THREAD

**Issue by arkioooo** [chunky-dev/chunky#1160]
I try to start chunky and it leaves me with this message in the debug console:
**Exception in thread "main" java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1643)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at se.llbit.chunky.resources.TexturePackLoader.loadTextures(TexturePackLoader.java:3689)
	at se.llbit.chunky.resources.TexturePackLoader.loadTexturePacks(TexturePackLoader.java:3781)
	at se.llbit.chunky.resources.TexturePackLoader.loadTexturePacks(TexturePackLoader.java:3747)
	at se.llbit.chunky.main.CommandLineOptions.<init>(CommandLineOptions.java:493)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:202)
Chunky exited abnormally with exit value 1**

It says failed to start and shows that the following command was used to launch chunky : 
**C:\Program Files\Java\jre1.8.0_321\bin\java.exe -Xmx8374m -Dchunky.home=C:\Users\admin\.chunky -Dprism.order=sw -classpath C:\Users\admin\.chunky\lib\chunky-core-2.5.0-50-gdb566e99.jar;C:\Users\admin\.chunky\lib\commons-math3-3.2.jar;C:\Users\admin\.chunky\lib\fastutil-8.4.4.jar se.llbit.chunky.main.Chunky**

It worked fine for me previus week when I opened it, but today it showed this problem. I tried to uninstall and reinstall java and chunky and restarted the PC, no change. The drivers and windows is upto date and Chunky previously did work on it. No other significant change was done in my PC.

**Comment by arkioooo** [comment]
It worked fine for me previus week when I opened it, but today it showed this problem

**Comment by NotStirred** [comment]
this was an issue with one of the snapshots around a week or so, does updating to latest fix it?

**Comment by arkioooo** [comment]
> this was an issue with one of the snapshots around a week ago or so, does updating to latest fix it?

I just tried reinstalling java and  then chunky and it worked. I should close the issue now

**Comment by NotStirred** [comment]
reinstalling both should be unnecessary, just updating chunky through the launcher should have fixed it

glad you got it working :+1:
