### ISSUE TITLE
will not run chunky due to javafx

### ISSUE THREAD

**Issue by MaxSchuck** [chunky-dev/chunky#1161]
I am using Windows 10 Version 10.0.19043 (my family has set up a domain in which my pc is registered in case that matters), java version 17, openjfx 17.0.2 sdk and  chunky launcher v1.13.1

I first tried installing directly in a folder in Program Files, but the console allready threw me an error stating it was unable to find javafx.controls. So i thought it might have trouble with permissions in C: because i have had that before. 

So i went ahead and installed via the same cmd command: but a slightly different path:
` java --module-path D:\chunky\OpenJFX\lib --add-modules javafx.controls,javafx.fxml -jar D:\chunky/ChunkyLauncher.jar`
it seemed to work fine, chunky launcher installed, I got myself an up2date chunky version via the update button, but as i try to run it I get told see the debug console, which informs me with:

```
Unchecked exception caused Chunky to close.
java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:224)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more

Chunky exited abnormally with exit value 2
```

which leaves me as stupid as i was before, and I dont know where to find help, thats why i hope someone here can tell my what I am doing wrong

**Comment by Peregrine05** [comment]
You need to populate the Java options field in the Chunky launcher with the following text.

`--module-path "D:\chunky\OpenJFX\lib" --add-modules javafx.controls,javafx.fxml`

If there is already some text in that text box, then paste it in before that text, and add a space.

**Comment by MaxSchuck** [comment]
> --module-path "D:\chunky\OpenJFX\lib" --add-modules javafx.controls,javafx.fxml

works, perfect, thank you...  do I delete this issue or leave it open for other fools? ;P

**Comment by Peregrine05** [comment]
Just close the issue, I think.
