### ISSUE TITLE
Unchecked exception caused Chunky to close.

### ISSUE THREAD

**Issue by Timtaran** [chunky-dev/chunky#1200]
```
Unchecked exception caused Chunky to close.
java.lang.NoClassDefFoundError: javafx/application/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at se.llbit.chunky.main.Chunky.main(Chunky.java:224)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 10 more
```

**Comment by jackjt8** [comment]
Is this exception showing up when launching Chunkylauncher or Chunky itself?

If it's the latter you need to manually add `--module-path` and `--add-modules` to the `Java Options` field within the launcher. It only auto populates when it automatically finds Javafx and not when it's done so manually.

**Comment by leMaik** [comment]
Closing due to lack of response. Feel free to reopen if you still can't launch Chunky or reach out to us on Discord. :upside_down_face:

**Comment by JesseChin** [comment]
I had this same issue, @jackjt8's suggestion fixed it.
