### ISSUE TITLE
crc corruption Java 8 issue 2.4+

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1207]
Works in Chunky 2.3.0 with Java 8
Fails in Chunky 2.4.0+ with Java 8

Pack - 
Mombasa 1.18 (32x)
https://www.mediafire.com/file/q5ja35n1zphvm99/Mombasa_1.18_%252832x%2529.zip/file

```
sun.awt.image.PNGImageDecoder$PNGException: crc corruption
	at sun.awt.image.PNGImageDecoder.getChunk(Unknown Source)
	at sun.awt.image.PNGImageDecoder.getData(Unknown Source)
	at sun.awt.image.PNGImageDecoder.produceImage(Unknown Source)
	at sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at sun.awt.image.ImageFetcher.run(Unknown Source)
sun.awt.image.PNGImageDecoder$PNGException: crc corruption
	at sun.awt.image.PNGImageDecoder.getChunk(Unknown Source)
	at sun.awt.image.PNGImageDecoder.getData(Unknown Source)
	at sun.awt.image.PNGImageDecoder.produceImage(Unknown Source)
	at sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at sun.awt.image.ImageFetcher.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at se.llbit.resources.ImageLoader.fromAwtImage(ImageLoader.java:150)
	at se.llbit.resources.ImageLoader.read(ImageLoader.java:101)
	at se.llbit.chunky.resources.texturepack.SimpleTexture.load(SimpleTexture.java:44)
	at se.llbit.chunky.resources.texturepack.TextureLoader.load(TextureLoader.java:79)
	at se.llbit.chunky.resources.texturepack.SimpleTexture.load(SimpleTexture.java:66)
	at se.llbit.chunky.resources.texturepack.AlternateTextures.load(AlternateTextures.java:54)
	at se.llbit.chunky.resources.TexturePackLoader.loadTextures(TexturePackLoader.java:3709)
	at se.llbit.chunky.resources.TexturePackLoader.loadTexturePacks(TexturePackLoader.java:3769)
	at se.llbit.chunky.ui.dialogs.ResourceLoadOrderEditor.lambda$new$0(ResourceLoadOrderEditor.java:59)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by jackjt8** [comment]
@leMaik

**Comment by jackjt8** [comment]
Workaround is to update to `Java 17`.

**Comment by ThatRedox** [comment]
Some of the textures have corrupted chunks:
```
pngcheck -cvt brown_glazed_terracotta.png
File: brown_glazed_terracotta.png (6746 bytes)
  chunk IHDR at offset 0x0000c, length 13
    32 x 32 image, 32-bit RGB+alpha, non-interlaced
  chunk zTXt at offset 0x00025, length 2097, keyword: Raw profile type exif
    (compressed zTXt text)
  chunk iCCP at offset 0x00862, length 389
    profile name = ICC PROFILE, compression method = 0 (deflate)
    compressed profile = 376 bytes
  CRC error in chunk iCCP (computed d0480949, expected e94f09f1)
ERRORS DETECTED in brown_glazed_terracotta.png
```
Full list of corrupted textures: [corrupted.txt](https://github.com/chunky-dev/chunky/files/8318168/corrupted.txt)
