### ISSUE TITLE
Chunk loading crash

### ISSUE THREAD

**Issue by leMaik** [chunky-dev/chunky#1238]
Latest snapshot, see #help in Discord

```
Scene manager has crashed due to an uncaught exception. Chunky will not work properly until you restart it. If you think this is a bug, please report it to the developers.
java.util.ConcurrentModificationException
    at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
    at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
    at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1278)
    at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadFreshChunks(SynchronousSceneManager.java:228)
    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadFreshChunks$4(AsynchronousSceneManager.java:160)
    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:81)
```

**Comment by Peregrine05** [comment]
Specifically, go here:
https://discord.com/channels/541221265512464394/571769711402942467/966405041135165440
