### ISSUE TITLE
Sign crashes when loaded due to out of bounds text on the image (debug only assertion)

### ISSUE THREAD

**Issue by NotStirred** [chunky-dev/chunky#1259]
see attached world to reproduce

```
Exception in thread "Scene Manager" java.lang.AssertionError
	at se.llbit.chunky.resources.PalettizedBitmapImage.setPixel(PalettizedBitmapImage.java:37)
	at se.llbit.chunky.resources.SignTexture.<init>(SignTexture.java:100)
	at se.llbit.chunky.entity.WallSignEntity.<init>(WallSignEntity.java:103)
	at se.llbit.chunky.entity.WallSignEntity.<init>(WallSignEntity.java:95)
	at se.llbit.chunky.block.WallSign.toBlockEntity(WallSign.java:48)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1314)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadFreshChunks(SynchronousSceneManager.java:230)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadFreshChunks$4(AsynchronousSceneManager.java:161)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:82)
```

[crashy sign.zip](https://github.com/chunky-dev/chunky/files/8664689/crashy.sign.zip)

**Comment by Peregrine05** [comment]
I cannot reproduce this in the latest snapshot by simply loading all chunks in the world with `Load entities > Other` enabled. Am I missing something, or was this bug fixed at some point?

**Comment by Peregrine05** [comment]
I do not know how to enable assertions, so I do not think that they were enabled. The debug console and verbose logging are enabled, though.

**Comment by leMaik** [comment]
Logging will not enable assertions, so you can't possibly reproduce this.
