### ISSUE TITLE
Chunky error when trying to load builds bigger than the vanilla height (1500x1500)

### ISSUE THREAD

**Issue by dancsa222** [chunky-dev/chunky#1262]
Hi! I tried loading up a 1500x1500 sphere in chunky and got this error:

Scene manager has crashed due to an uncaught exception. Chunky will not work properly until you restart it. If you think this is a bug, please report it to the developers.
java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: begin 10, end 9, length 9
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:997)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadChunks(SynchronousSceneManager.java:240)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadChunks$5(AsynchronousSceneManager.java:168)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:81)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 10, end 9, length 9
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.substring(String.java:1907)
	at java.base/java.lang.String.substring(String.java:1880)
	at se.llbit.chunky.block.MinecraftBlockProvider.getBlockByTag(MinecraftBlockProvider.java:997)
	at se.llbit.chunky.block.BlockSpec.toBlock(BlockSpec.java:51)
	at se.llbit.chunky.chunk.BlockPalette.put(BlockPalette.java:124)
	at se.llbit.chunky.chunk.BlockPalette.put(BlockPalette.java:108)
	at se.llbit.chunky.world.Chunk.loadBlockData(Chunk.java:266)
	at se.llbit.chunky.world.Chunk.getChunkData(Chunk.java:456)
	at se.llbit.chunky.renderer.scene.Scene.lambda$loadChunks$1(Scene.java:1015)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

Exported Chunks:
[SPACE EMPIRE.zip](https://github.com/chunky-dev/chunky/files/8695192/SPACE.EMPIRE.zip)

**Comment by NotStirred** [comment]
This is unrelated to world height, I believe fixed by #1265

**Comment by NotStirred** [comment]
An additional fix in #1283 due to trying to load empty chunks with the new selection logic
