### ISSUE TITLE
java.io.IOException: Failed to parse BiomeStructure (TRIVIAL_3D) from octree data

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1289]
When loading this scene: [https://www.dropbox.com/s/usi69bfht38c6lu/benchmark_test_scene.zip?dl=0](https://www.dropbox.com/s/usi69bfht38c6lu/benchmark_test_scene.zip?dl=0)

The following error occurs:
```
Failed to load chunk data!
java.io.IOException: Failed to parse BiomeStructure (TRIVIAL_3D) from octree data
	at se.llbit.chunky.resources.OctreeFileFormat.loadBiomeStructure(OctreeFileFormat.java:87)
	at se.llbit.chunky.resources.OctreeFileFormat.load(OctreeFileFormat.java:64)
	at se.llbit.chunky.renderer.scene.Scene.loadOctree(Scene.java:2323)
	at se.llbit.chunky.renderer.scene.Scene.loadScene(Scene.java:617)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadScene(SynchronousSceneManager.java:203)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadScene$0(AsynchronousSceneManager.java:111)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:86)
Caused by: java.lang.NegativeArraySizeException: -1
	at se.llbit.chunky.renderer.scene.biome.BiomeStructure$1.load(BiomeStructure.java:50)
	at se.llbit.chunky.resources.OctreeFileFormat.loadBiomeStructure(OctreeFileFormat.java:83)
	... 6 more
```

**Comment by Peregrine05** [comment]
When saving the scene, the following error occurs:
```
Scene manager has crashed due to an uncaught exception. Chunky will not work properly until you restart it. If you think this is a bug, please report it to the developers.
java.lang.NullPointerException: Cannot invoke "se.llbit.chunky.renderer.scene.biome.BiomeStructure.biomeFormat()" because "grassColors" is null
    at se.llbit.chunky.resources.OctreeFileFormat.store(OctreeFileFormat.java:170)
    at se.llbit.chunky.renderer.scene.Scene.saveOctree(Scene.java:2266)
    at se.llbit.chunky.renderer.scene.Scene.saveScene(Scene.java:564)
    at se.llbit.chunky.renderer.scene.SynchronousSceneManager.saveScene(SynchronousSceneManager.java:184)
    at se.llbit.chunky.renderer.scene.SynchronousSceneManager.saveScene(SynchronousSceneManager.java:145)
    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$saveScene$3(AsynchronousSceneManager.java:153)
    at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:86)
```
