### ISSUE TITLE
Render worker 9 crashed with uncaught exception. java.lang.NullPointerException: Cannot load from float array because "tintColor" is null

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1299]
The following Discord discussions are based on this issue.
[https://discord.com/channels/541221265512464394/571769711402942467/980430937676447764](https://discord.com/channels/541221265512464394/571769711402942467/980430937676447764)
[https://discord.com/channels/541221265512464394/571769711402942467/984744633479348234](https://discord.com/channels/541221265512464394/571769711402942467/984744633479348234)
```
Render worker 9 crashed with uncaught exception.
java.lang.NullPointerException: Cannot load from float array because "tintColor" is null
    at se.llbit.chunky.model.Tint.tint(Tint.java:82)
    at se.llbit.chunky.model.AABBModel.intersectFace(AABBModel.java:145)
    at se.llbit.chunky.model.AABBModel.intersect(AABBModel.java:77)
    at se.llbit.chunky.block.AbstractModelBlock.intersect(AbstractModelBlock.java:28)
    at se.llbit.math.Octree.enterBlock(Octree.java:537)
    at se.llbit.chunky.renderer.scene.Scene.worldIntersection(Scene.java:794)
    at se.llbit.chunky.renderer.scene.Scene.intersect(Scene.java:770)
    at se.llbit.chunky.renderer.scene.PreviewRayTracer.nextIntersection(PreviewRayTracer.java:98)
    at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(PathTracer.java:70)
    at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(PathTracer.java:226)
    at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(PathTracer.java:226)
    at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(PathTracer.java:226)
    at se.llbit.chunky.renderer.scene.PathTracer.pathTrace(PathTracer.java:226)
    at se.llbit.chunky.renderer.scene.PathTracer.trace(PathTracer.java:50)
    at se.llbit.chunky.renderer.scene.Scene.rayTrace(Scene.java:737)
    at se.llbit.chunky.renderer.PathTracingRenderer.lambda$render$0(PathTracingRenderer.java:83)
    at se.llbit.chunky.renderer.TileBasedRenderer.lambda$submitTiles$1(TileBasedRenderer.java:82)
    at se.llbit.chunky.renderer.RenderWorkerPool.work(RenderWorkerPool.java:141)
    at se.llbit.chunky.renderer.RenderWorkerPool.access$100(RenderWorkerPool.java:29)
    at se.llbit.chunky.renderer.RenderWorkerPool$RenderWorker.run(RenderWorkerPool.java:101)
```
It appears that it happens when a large selection of chunks are loaded.

**Comment by jackjt8** [comment]
If anyone is experiencing this issue please attempt to use [`VisualVM`](https://visualvm.github.io/) and get a `Heap Dump` once this crops up. We may be able to explore the dump to figure out what exactly is going wrong.
