### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException at se.llbit.chunky.resources.PalettizedBitmapImage.setPixel

### ISSUE THREAD

**Issue by 2138550057** [chunky-dev/chunky#1440]
Scene manager has crashed due to an uncaught exception. Chunky will not work properly until you restart it. If you think this is a bug, please report it to the developers.
java.lang.ArrayIndexOutOfBoundsException: Index -32 out of bounds for length 2304
	at se.llbit.chunky.resources.PalettizedBitmapImage.setPixel(PalettizedBitmapImage.java:41)
	at se.llbit.chunky.resources.SignTexture.<init>(SignTexture.java:100)
	at se.llbit.chunky.entity.WallSignEntity.<init>(WallSignEntity.java:103)
	at se.llbit.chunky.entity.WallSignEntity.<init>(WallSignEntity.java:95)
	at se.llbit.chunky.block.WallSign.toBlockEntity(WallSign.java:48)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1294)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadFreshChunks(SynchronousSceneManager.java:167)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadFreshChunks$2(AsynchronousSceneManager.java:131)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:80)

（Map version:1.19.1）
Use conversion tool to switch from bedrock edition to Java

**Comment by leMaik** [comment]
Probably the same as #1259

**Comment by 2138550057** [comment]
OK, I have updated the latest snapshot version and can render normally. Thank you

**Comment by leMaik** [comment]
We should see what the fix is and backport it to 2.4.x. @2138550057 Could you still send us the chunks/world that failed to load?

**Comment by 2138550057** [comment]
> 我们应该看看修复是什么并将其反向移植到 2.4.x。@2138550057你还能把加载失败的区块/世界发给我们吗？

OK, what's your email address

**Comment by Peregrine05** [comment]
Was the fix #1242?

https://discord.com/channels/541221265512464394/571769711402942467/967389935818653706

**Comment by leMaik** [comment]
@Peregrine05 Great catch, I cherry-picked the fix and it will be released in 2.4.4. We should figure out why signs cause the oob access, so I'll leave #1259 open until we have fixed _that_ (and not the symptoms).
