### ISSUE TITLE
Error when Map `Max Y level` is less than `Min Y level`

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1444]
When the Map `Max Y level` is set less than the `Min Y level`, the following error occurs. Chunky remains fully functional.
```
Region Parser Error
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at se.llbit.chunky.world.biome.ArrayBiomePalette.get(ArrayBiomePalette.java:29)
	at se.llbit.chunky.map.BiomeLayer.<init>(BiomeLayer.java:41)
	at se.llbit.chunky.world.Chunk.loadSurface(Chunk.java:191)
	at se.llbit.chunky.world.Chunk.loadChunk(Chunk.java:172)
	at se.llbit.chunky.world.region.RegionParser.run(RegionParser.java:72)
```

**Comment by Peregrine05** [comment]
@ThatRedox 

https://user-images.githubusercontent.com/92183530/193465509-30afa186-c78f-49f3-99f1-0d4e8cdcf3e2.mp4
[1_19 Test.zip](https://github.com/chunky-dev/chunky/files/9693014/1_19.Test.zip)

Some worlds never seem to produce the error, while others do readily. The world above is one such world.

The world immediately below does not produce the error as readily, if even at all.
[Editor test.zip](https://github.com/chunky-dev/chunky/files/9693024/Editor.test.zip)
