### ISSUE TITLE
Failed to download skin - Greenfield 0.5.4

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1470]
```Failed to download skin from http://textures.minecraft.net/texture/d987cf1202a49b6107d8f867de57c6c0279750793da1a014c6fa20a796a7c294
java.io.FileNotFoundException: http://textures.minecraft.net/texture/d987cf1202a49b6107d8f867de57c6c0279750793da1a014c6fa20a796a7c294
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at se.llbit.util.mojangapi.MojangApi.downloadSkin(MojangApi.java:135)
	at se.llbit.chunky.entity.HeadEntity.lambda$downloadTexture$0(HeadEntity.java:160)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at se.llbit.chunky.entity.HeadEntity.downloadTexture(HeadEntity.java:156)
	at se.llbit.chunky.entity.HeadEntity.downloadSkin(HeadEntity.java:181)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:125)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:119)
	at dev.ferrand.chunky.bvh.implementation.PackedSahMaBVH$1.create(PackedSahMaBVH.java:38)
	at se.llbit.math.bvh.BVH$Factory.create(BVH.java:102)
	at se.llbit.chunky.renderer.scene.Scene.buildBvh(Scene.java:1556)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1544)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadChunks(SynchronousSceneManager.java:275)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadChunks$9(AsynchronousSceneManager.java:214)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:92)
```
```
Failed to download skin from http://textures.minecraft.net/texture/26f7805733551fa6cbe369822664df4f551563950c48caf868069d185cb4c009
java.io.FileNotFoundException: http://textures.minecraft.net/texture/26f7805733551fa6cbe369822664df4f551563950c48caf868069d185cb4c009
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at se.llbit.util.mojangapi.MojangApi.downloadSkin(MojangApi.java:135)
	at se.llbit.chunky.entity.HeadEntity.lambda$downloadTexture$0(HeadEntity.java:160)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at se.llbit.chunky.entity.HeadEntity.downloadTexture(HeadEntity.java:156)
	at se.llbit.chunky.entity.HeadEntity.downloadSkin(HeadEntity.java:181)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:125)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:119)
	at dev.ferrand.chunky.bvh.implementation.PackedSahMaBVH$1.create(PackedSahMaBVH.java:38)
	at se.llbit.math.bvh.BVH$Factory.create(BVH.java:102)
	at se.llbit.chunky.renderer.scene.Scene.buildBvh(Scene.java:1556)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1544)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadChunks(SynchronousSceneManager.java:275)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadChunks$9(AsynchronousSceneManager.java:214)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:92)
```
```
Failed to download skin from http://textures.minecraft.net/texture/4e32f4a4c36a21a83589132e599e7cc46af76f5d0d3efc92da3e0cbfe8dc7
java.io.FileNotFoundException: http://textures.minecraft.net/texture/4e32f4a4c36a21a83589132e599e7cc46af76f5d0d3efc92da3e0cbfe8dc7
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at se.llbit.util.mojangapi.MojangApi.downloadSkin(MojangApi.java:135)
	at se.llbit.chunky.entity.HeadEntity.lambda$downloadTexture$0(HeadEntity.java:160)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at se.llbit.chunky.entity.HeadEntity.downloadTexture(HeadEntity.java:156)
	at se.llbit.chunky.entity.HeadEntity.downloadSkin(HeadEntity.java:181)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:125)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:119)
	at dev.ferrand.chunky.bvh.implementation.PackedSahMaBVH$1.create(PackedSahMaBVH.java:38)
	at se.llbit.math.bvh.BVH$Factory.create(BVH.java:102)
	at se.llbit.chunky.renderer.scene.Scene.buildBvh(Scene.java:1556)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1544)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadChunks(SynchronousSceneManager.java:275)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadChunks$9(AsynchronousSceneManager.java:214)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:92)
```
```
Failed to download skin from http://textures.minecraft.net/texture/1789b3e2868d716a921dec5932d530a892f600235f187766bc02d145ed16865b
java.io.FileNotFoundException: http://textures.minecraft.net/texture/1789b3e2868d716a921dec5932d530a892f600235f187766bc02d145ed16865b
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at se.llbit.util.mojangapi.MojangApi.downloadSkin(MojangApi.java:135)
	at se.llbit.chunky.entity.HeadEntity.lambda$downloadTexture$0(HeadEntity.java:160)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at se.llbit.chunky.entity.HeadEntity.downloadTexture(HeadEntity.java:156)
	at se.llbit.chunky.entity.HeadEntity.downloadSkin(HeadEntity.java:181)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:125)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:119)
	at dev.ferrand.chunky.bvh.implementation.PackedSahMaBVH$1.create(PackedSahMaBVH.java:38)
	at se.llbit.math.bvh.BVH$Factory.create(BVH.java:102)
	at se.llbit.chunky.renderer.scene.Scene.buildBvh(Scene.java:1556)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1544)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadChunks(SynchronousSceneManager.java:275)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadChunks$9(AsynchronousSceneManager.java:214)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:92)
```
```
Failed to download skin from http://textures.minecraft.net/texture/9c250b47e10a50d69166cb0ecaf234100cae7899a4898108c1307017a5a7ebb3
java.io.FileNotFoundException: http://textures.minecraft.net/texture/9c250b47e10a50d69166cb0ecaf234100cae7899a4898108c1307017a5a7ebb3
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at se.llbit.util.mojangapi.MojangApi.downloadSkin(MojangApi.java:135)
	at se.llbit.chunky.entity.HeadEntity.lambda$downloadTexture$0(HeadEntity.java:160)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at se.llbit.chunky.entity.HeadEntity.downloadTexture(HeadEntity.java:156)
	at se.llbit.chunky.entity.HeadEntity.downloadSkin(HeadEntity.java:181)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:125)
	at se.llbit.chunky.entity.HeadEntity.primitives(HeadEntity.java:119)
	at dev.ferrand.chunky.bvh.implementation.PackedSahMaBVH$1.create(PackedSahMaBVH.java:38)
	at se.llbit.math.bvh.BVH$Factory.create(BVH.java:102)
	at se.llbit.chunky.renderer.scene.Scene.buildBvh(Scene.java:1556)
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:1544)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadChunks(SynchronousSceneManager.java:275)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadChunks$9(AsynchronousSceneManager.java:214)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:92)
```

**Comment by leMaik** [comment]
Can this still be reproduced? The files seem to be available now, maybe it was a temporary issue?

**Comment by jackjt8** [comment]
Temporary server issue it seems.
