### ISSUE TITLE
Failed to load chunk data! java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1569]
On the latest snapshot, this [scene](https://drive.google.com/file/d/1_QJ-PXPwRBbJLOkNJCwqaanvd6497V0c/view?usp=share_link) fails to load with the following error:
```
Failed to load chunk data!
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at it.unimi.dsi.fastutil.io.FastBufferedInputStream.noMoreCharacters(FastBufferedInputStream.java:181)
	at it.unimi.dsi.fastutil.io.FastBufferedInputStream.read(FastBufferedInputStream.java:193)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:395)
	at java.base/java.io.DataInputStream.readFloat(DataInputStream.java:452)
	at se.llbit.chunky.world.ChunkTexture.load(ChunkTexture.java:94)
	at se.llbit.chunky.world.WorldTexture.load(WorldTexture.java:114)
	at se.llbit.chunky.renderer.scene.biome.WorldTexture2dBiomeStructure.load(WorldTexture2dBiomeStructure.java:19)
	at se.llbit.chunky.resources.OctreeFileFormat.loadBiomeStructure(OctreeFileFormat.java:86)
	at se.llbit.chunky.resources.OctreeFileFormat.load(OctreeFileFormat.java:65)
	at se.llbit.chunky.renderer.scene.Scene.loadOctree(Scene.java:2333)
	at se.llbit.chunky.renderer.scene.Scene.loadScene(Scene.java:586)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.loadScene(SynchronousSceneManager.java:195)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.lambda$loadScene$0(AsynchronousSceneManager.java:117)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:92)
```
`Kr0wn#6503` created the scene, and may be able to provide more information. `Kr0wn#6503` is a member of the Chunky Discord server.

**Comment by leMaik** [comment]
This is a world loading issue, so we need the world files to further investigate this bug.
