### ISSUE TITLE
Running Chunky with Java 11

### ISSUE THREAD

**Issue by DrBlackross** [chunky-dev/chunky#523]
same thing, java was 11, knocked down to 8, uninstalled/reinstalled openjfx in both versions...

---------------------------------\/- the stuff i get -\/-----------------

sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 

BEAST:~/Downloads$  java -jar ./ChunkyLauncher.jar --verbose
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -Dchunky.home=/home/drblackross/.chunky -classpath /home/drblackross/.chunky/lib/chunky-core-1.4.5.jar:/home/drblackross/.chunky/lib/commons-math3-3.2.jar se.llbit.chunky.main.Chunky
Unchecked exception caused Chunky to close.
java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:214)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

Failed to launch Chunky. Command used:
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -Dchunky.home=/home/drblackross/.chunky -classpath /home/drblackross/.chunky/lib/chunky-core-1.4.5.jar:/home/drblackross/.chunky/lib/commons-math3-3.2.jar se.llbit.chunky.main.Chunky

BEAST:~/Downloads$ sudo apt-get install openjfx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjfx is already the newest version (11.0.2+1-1~18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

no matter what is done i still end up at...

BEAST:~/Downloads$  java -jar ./ChunkyLauncher.jar 
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/Stage
	at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:273)
	at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:194)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Stage
	... 2 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

BEAST:~/Downloads$ sudo apt-get install openjfx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjfx is already the newest version (11.0.2+1-1~18.04.2). <------ i don't think is an issue 
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

------------------------------------------------------------------------------

i can run Chunky on windows 10,  yes... but it will only render a blue square at whatever size i choose as a output size in tiff or png lol

been using this tut, for the windows 10 system (didn't know about f3) 
https://chunky.llbit.se/your_first_render.html

my surface pro is the only windows 10 machine in my house (hell even the house is linux lol)

I haven't tried running chunky as root (but i shouldn't have too, right?).

sooooo this is where i am, i don't think its a new issue, but i'm willing to bet i am over looking something.

**Comment by DrBlackross** [comment]
ZOMG

i had to bring java up to 12, then install https://openjfx.io/openjfx-docs/#install-javafx (version 11)

@BEAST:~/Downloads$ java --module-path /home/drblackross/Downloads/javafx-sdk-11.0.2/lib/ --add-modules javafx.controls,javafx.fxml -jar ChunkyLauncher.jar

(the javafx i just dumped to my downloads folder and it worked from there)

Then BOOM

works LOL

**Comment by DrBlackross** [comment]
crashes after trying to launch

soooo just tried to launch the core file itself as a lark

@BEAST:~/Downloads$ java --module-path /home/drblackross/Downloads/javafx-sdk-11.0.2/lib/ --add-modules javafx.controls,javafx.fxml -jar /home/drblackross/.chunky/lib/chunky-core-1.4.5.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/math3/util/FastMath
	at se.llbit.chunky.resources.Texture.setTexture(Texture.java:702)
	at se.llbit.chunky.resources.Texture.<init>(Texture.java:681)
	at se.llbit.chunky.resources.Texture.<init>(Texture.java:673)
	at se.llbit.chunky.resources.Texture$1.<init>(Texture.java:41)
	at se.llbit.chunky.resources.Texture.<clinit>(Texture.java:41)
	at se.llbit.chunky.resources.TexturePackLoader.<clinit>(TexturePackLoader.java:65)
	at se.llbit.chunky.main.CommandLineOptions.<init>(CommandLineOptions.java:421)
	at se.llbit.chunky.main.Chunky.main(Chunky.java:194)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math3.util.FastMath
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more


.... :(

**Comment by llbit** [comment]
Chunky is much easier to run with Java 8, which has JavaFX built-in.

If you run on Java 11 you will probably have to add `--module-path` and `--add-modules` options to the command for starting the Chunky launcher and then add the same options in the `Java options` field under `Advanced` inside the Chunky launcher. I haven't tried this myself yet.

**Comment by rveachkc** [comment]
> Chunky is much easier to run with Java 8, which has JavaFX built-in.
> 
> If you run on Java 11 you will probably have to add `--module-path` and `--add-modules` options to the command for starting the Chunky launcher and then add the same options in the `Java options` field under `Advanced` inside the Chunky launcher. I haven't tried this myself yet.

Thanks for this tip.  I was able to get this running on Ubuntu 19.04, bionic with the following:

```bash
java --module-path /usr/share/maven-repo/org/openjfx/javafx-controls/11/:/usr/share/maven-repo/org/openjfx/javafx-base/11/:/usr/share/maven-repo/org/openjfx/javafx-graphics/11/:/usr/share/maven-repo/org/openjfx/javafx-fxml/11/ --add-modules=javafx.controls,javafx.base,javafx.graphics,javafx.fxml -jar /home/ryan/Downloads/chunky-1.4.5.jar
```

after installing:
libopenjfx-java and libcontrolsfx-java

**Comment by jackjt8** [comment]
Better late than never.

For getting OpenJDK 11 + OpenJFX working on Windows the process is largely the same however you need to delete `jrt-fs.jar` otherwise you will run into an error when attempting to launch Chunky - `java.lang.LayerInstantiationException: Package jdk.internal.jimage in both module java.base and module jrt.fs`.

An example .bat file (located in the same directory as ChunkyLauncher.jar):

```
cd /d %~dp0
java --module-path "C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\lib" --add-modules=javafx.controls,javafx.base,javafx.graphics,javafx.fxml -jar ChunkyLauncher.jar --launcher
pause
```

And the required `Java Options` in the Launcher: `--module-path "C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\lib" --add-modules=javafx.controls,javafx.base,javafx.graphics,javafx.fxml`

---

You may run into some poor scaling and blurry UI compared to Oracle Java 8 but this may be a system configuration.

**Comment by douira** [comment]
I'm on macOS. For some reason I can't pass java options like `--module-path=/Users/me/path\ to\ jfx/javafx-sdk-16/lib  --add-modules=javafx.controls,javafx.base,javafx.graphics,javafx.fxml` if the path contains spaces. Enclosing it in quotes or escaping with backslashes didn't work and resulted in a "class not found: path\" error.

**Comment by Huskydog9988** [comment]
I could just be nitpicking your example, but could the issue be the commingling of both `/` and `\` in the path?

**Comment by douira** [comment]
`/` is the normal path separator while `\` escapes the spaces. This is macOS where unlike on Windows `\` is not a path separator.
