### ISSUE TITLE
Issue with snow crashing render preview 

### ISSUE THREAD

**Issue by Versai24** [chunky-dev/chunky#687]
Not sure where is coming from, crash happens when I zoom out in the render preview.

Render worker 2 crashed with uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: -1
	at se.llbit.chunky.model.SnowModel.intersect(SnowModel.java:71)
	at se.llbit.chunky.block.Snow.intersect(Snow.java:18)
	at se.llbit.math.PackedOctree.enterBlock(PackedOctree.java:493)
	at se.llbit.math.Octree.enterBlock(Octree.java:347)
	at se.llbit.chunky.renderer.scene.Scene.worldIntersection(Scene.java:634)
	at se.llbit.chunky.renderer.scene.Scene.intersect(Scene.java:610)
	at se.llbit.chunky.renderer.scene.PreviewRayTracer.nextIntersection(PreviewRayTracer.java:95)
	at se.llbit.chunky.renderer.scene.PreviewRayTracer.trace(PreviewRayTracer.java:44)
	at se.llbit.chunky.renderer.scene.Scene.rayTrace(Scene.java:590)
	at se.llbit.chunky.renderer.RenderWorker.work(RenderWorker.java:185)
	at se.llbit.chunky.renderer.RenderWorker.run(RenderWorker.java:73)

**Comment by leMaik** [comment]
@Versai24 This will be fixed in the next snapshot. Did this happen in a world that was converted from Bedrock or with a Java edition world?

**Comment by Versai24** [comment]
World was converted from bedrock edition yes.

**Comment by leMaik** [comment]
Then the converter probably has a bug. In Java edition, the snow levels are 1-8, in bedrock they are 0-7. Nothing we can fix here, but the workaround now clamps them, so they will be 1-7 for your world.
