### ISSUE TITLE
Not starting with Java 14 on Linux

### ISSUE THREAD

**Issue by slinkouswasalreadytaken** [chunky-dev/chunky#757]
when running the java on the version downloaded from the website, I am receiving the following error:
```
~ >>> java -jar /home/slinkous/Downloads/ChunkyLauncher.jar                                                                                                   
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/stage/Stage
        at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:274)
        at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:192)
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more
~ >>>               
```

I am using manjaro linux stable.

**Comment by leMaik** [comment]
Looks like you don't have OpenJfx installed. See #523 and #484

**Comment by slinkouswasalreadytaken** [comment]
I installed java-openjfx 14, and my java version is also 14, but running the same command does nothing different...

**Comment by leMaik** [comment]
Allright. You'll have to specify some modules so that Java actually finds openjfx. See this comment: https://github.com/chunky-dev/chunky/issues/523#issuecomment-710379089

**Comment by slinkouswasalreadytaken** [comment]
I am currently on linux, so am using java-openjfx. I'm assuming that's why the following command is giving me this error?

```
~ >>> java --add-modules=javafx.controls,javafx.base,javafx.graphics,javafx.fxml -jar /home/slinkous/Downloads/ChunkyLauncher.jar                             
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.base not found
~ >>>         ```

**Comment by leMaik** [comment]
@slinkouswasalreadytaken As described in the comment I linked, you also need to add `--module-path`. I missed it in the TL;DR. Don't ask me where it needs to point to on your system, but I hope that Google knows that.

**Comment by aTom3333** [comment]
Your command is missing the `--module-path <path/to/openjfx>` part (guess leMaik forgot about it).
On linux the full command is probably `java --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml -jar /home/slinkous/Downloads/ChunkyLauncher.jar`

**Comment by leMaik** [comment]
@aTom3333 Thx, I updated my comment above.

**Comment by aTom3333** [comment]
For future reference, on debian based system, I can used `dpkg-query -L openjfx` to get the list of files installed by the package `openjfx`. The output is
```
...
/usr/share/openjfx
/usr/share/openjfx/lib
/usr/share/openjfx/lib/javafx.properties
/usr/share/openjfx/lib/javafx.base.jar
/usr/share/openjfx/lib/javafx.controls.jar
/usr/share/openjfx/lib/javafx.fxml.jar
/usr/share/openjfx/lib/javafx.graphics.jar
/usr/share/openjfx/lib/javafx.media.jar
/usr/share/openjfx/lib/javafx.swing.jar
/usr/share/openjfx/lib/javafx.web.jar
```
And that's how I can easily tell the path I need to use. If this path doesn't work, your package manager on your distribution probably have a similar command.

**Comment by slinkouswasalreadytaken** [comment]
ah, thanks, I couldn't find it in any of the usual places...

**Comment by slinkouswasalreadytaken** [comment]
Well this is strange... I am looking at the javafx.base, .controls, etc. in /usr/share/licenses, but the command is giving me this:

```
~ >>> java --module-path /usr/share/licenses/java-openjfx --add-modules javafx.controls,javafx.fxml -jar /home/slinkous/Downloads/ChunkyLauncher.jar                                                             [1]
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
~ >>>                                                                                                                                                                                                            [1]

```

**Comment by leMaik** [comment]
`/usr/share/licenses` isn't the place for libraries… What else does `dpkg-query -L openjfx` output?

**Comment by slinkouswasalreadytaken** [comment]
I am using manjaro so I am using pacman -Ql, and getting the following:

```
~ >>> yay -Ql java-openjfx                                                                                                                                 [1]
java-openjfx /usr/
java-openjfx /usr/lib/
java-openjfx /usr/lib/jvm/
java-openjfx /usr/lib/jvm/java-14-openjdk/
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/javafx.base.jmod
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/javafx.controls.jmod
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/javafx.fxml.jmod
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/javafx.graphics.jmod
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/javafx.media.jmod
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/javafx.swing.jmod
java-openjfx /usr/lib/jvm/java-14-openjdk/jmods/javafx.web.jmod
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx-swt.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.base.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.controls.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.fxml.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.graphics.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.media.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.properties
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.swing.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/javafx.web.jar
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libavplugin.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libdecora_sse.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libfxplugins.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libglass.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libglassgtk2.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libglassgtk3.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libgstreamer-lite.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libjavafx_font.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libjavafx_font_freetype.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libjavafx_font_pango.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libjavafx_iio.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libjfxmedia.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libjfxwebkit.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libprism_common.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libprism_es2.so
java-openjfx /usr/lib/jvm/java-14-openjdk/lib/libprism_sw.so
java-openjfx /usr/share/
java-openjfx /usr/share/licenses/
java-openjfx /usr/share/licenses/java-openjfx/
java-openjfx /usr/share/licenses/java-openjfx/javafx.base/
java-openjfx /usr/share/licenses/java-openjfx/javafx.base/ADDITIONAL_LICENSE_INFO
java-openjfx /usr/share/licenses/java-openjfx/javafx.base/ASSEMBLY_EXCEPTION
java-openjfx /usr/share/licenses/java-openjfx/javafx.base/LICENSE
java-openjfx /usr/share/licenses/java-openjfx/javafx.controls/
java-openjfx /usr/share/licenses/java-openjfx/javafx.controls/ADDITIONAL_LICENSE_INFO
java-openjfx /usr/share/licenses/java-openjfx/javafx.controls/ASSEMBLY_EXCEPTION
java-openjfx /usr/share/licenses/java-openjfx/javafx.controls/LICENSE
java-openjfx /usr/share/licenses/java-openjfx/javafx.fxml/
java-openjfx /usr/share/licenses/java-openjfx/javafx.fxml/ADDITIONAL_LICENSE_INFO
java-openjfx /usr/share/licenses/java-openjfx/javafx.fxml/ASSEMBLY_EXCEPTION
java-openjfx /usr/share/licenses/java-openjfx/javafx.fxml/LICENSE
java-openjfx /usr/share/licenses/java-openjfx/javafx.graphics/
java-openjfx /usr/share/licenses/java-openjfx/javafx.graphics/ADDITIONAL_LICENSE_INFO
java-openjfx /usr/share/licenses/java-openjfx/javafx.graphics/ASSEMBLY_EXCEPTION
java-openjfx /usr/share/licenses/java-openjfx/javafx.graphics/LICENSE
java-openjfx /usr/share/licenses/java-openjfx/javafx.graphics/jpeg_fx.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.graphics/mesa3d.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.media/
java-openjfx /usr/share/licenses/java-openjfx/javafx.media/ADDITIONAL_LICENSE_INFO
java-openjfx /usr/share/licenses/java-openjfx/javafx.media/ASSEMBLY_EXCEPTION
java-openjfx /usr/share/licenses/java-openjfx/javafx.media/LICENSE
java-openjfx /usr/share/licenses/java-openjfx/javafx.media/glib.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.media/gstreamer.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.media/libffi.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.swing/
java-openjfx /usr/share/licenses/java-openjfx/javafx.swing/ADDITIONAL_LICENSE_INFO
java-openjfx /usr/share/licenses/java-openjfx/javafx.swing/ASSEMBLY_EXCEPTION
java-openjfx /usr/share/licenses/java-openjfx/javafx.swing/LICENSE
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/ADDITIONAL_LICENSE_INFO
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/ASSEMBLY_EXCEPTION
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/LICENSE
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/icu_web.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/libxml2.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/libxslt.md
java-openjfx /usr/share/licenses/java-openjfx/javafx.web/webkit.md
~ >>>             ```

quite the output...

**Comment by leMaik** [comment]
@slinkouswasalreadytaken `--module-path /usr/lib/jvm/java-14-openjdk/lib` it is then :+1:

**Comment by aTom3333** [comment]
`/usr/lib/jvm/java-14-openjdk/lib/` seems to be the place

**Comment by slinkouswasalreadytaken** [comment]
ah, thanks

**Comment by slinkouswasalreadytaken** [comment]
-_-

```
~ >>> java --module-path /usr/lib/jvm/java-14-openjdk/lib --add-modules javafx.controls,javafx.fxml -jar /home/slinkous/Downloads/ChunkyLauncher.jar       [1]
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jimage.decompressor in both module java.base and module jrt.fs
~ >>>                                           
```

**Comment by leMaik** [comment]
Literally the first result on Google https://stackoverflow.com/a/57477801

**Comment by jackjt8** [comment]
Oh that one. Had that issue on windows.

Deleting `jrt-fs.jar` should fix it.. however this might not be the best solution.

**Comment by slinkouswasalreadytaken** [comment]
![Screenshot_20201222_112650](https://user-images.githubusercontent.com/53449377/102910455-97337c80-4448-11eb-8c56-dd02ba5a1304.png)

**Comment by leMaik** [comment]
@slinkouswasalreadytaken https://github.com/chunky-dev/chunky/issues/757#issuecomment-749612220 

> […] and also add it to the Java options in the launcher.

**Comment by aTom3333** [comment]
The same options need to be added in the java options field

**Comment by slinkouswasalreadytaken** [comment]
ah, right...

**Comment by slinkouswasalreadytaken** [comment]
Where would I edit that in?

**Comment by leMaik** [comment]
@slinkouswasalreadytaken In the _Java options_ field here:
![image](https://user-images.githubusercontent.com/5544859/102910799-70426e00-447b-11eb-9663-583861436dae.png)

**Comment by slinkouswasalreadytaken** [comment]
and here I was looking through the code of the .jar. XD

OK thanks so much...

**Comment by slinkouswasalreadytaken** [comment]
inputting the --module-path and --add-modules does absolutely nothing. Is there some format I should be following?

**Comment by slinkouswasalreadytaken** [comment]
![Screenshot_20201222_114329](https://user-images.githubusercontent.com/53449377/102912050-f7c3b900-444a-11eb-91cb-5450cc45d85a.png)

**Comment by leMaik** [comment]
@slinkouswasalreadytaken Can you copy/paste the command that was used to start Chunky from the _Launch error_ please?

**Comment by slinkouswasalreadytaken** [comment]
`/usr/lib/jvm/java-14-openjdk/bin/java -Xmx1024m -Dchunky.home=/home/slinkous/.chunky --module-path /usr/share/openjfx/lib --add-modules javafx.controls,javafx.fxml -classpath /home/slinkous/.chunky/lib/chunky-core-2.3.0.jar:/home/slinkous/.chunky/lib/commons-math3-3.2.jar -DlogLevel=INFO se.llbit.chunky.main.Chunky`

**Comment by aTom3333** [comment]
Is that the right path given to `--module-path`? Did you move javafx?

**Comment by slinkouswasalreadytaken** [comment]
I did not, I followed your advice on moving `jrt-fs.jar` to a different location, in this case my desktop.

**Comment by aTom3333** [comment]
So you entered the wrong `module-path`, yours is `/usr/lib/jvm/java-14-openjdk/lib`

**Comment by slinkouswasalreadytaken** [comment]
oh oops, copy pasted from an earlie (wrong) command

**Comment by slinkouswasalreadytaken** [comment]
Success! Thanks for your help!
