### ISSUE TITLE
Chunks not loaded after switching to One/ All emitter sampling

### ISSUE THREAD

**Issue by aBitterMelon** [chunky-dev/chunky#853]
Minecraft version 1.16.5, Chunky Version 2.4.0-98-GC64B83F1 

Some (not all) chunks seem to disappear when selecting One/All emitter sampling.

Debug:

Exception in thread "Scene Manager" java.lang.NullPointerException
	at se.llbit.chunky.renderer.scene.Scene.loadChunks(Scene.java:908)
	at se.llbit.chunky.renderer.scene.Scene.reloadChunks(Scene.java:782)
	at se.llbit.chunky.renderer.scene.SynchronousSceneManager.reloadChunks(SynchronousSceneManager.java:190)
	at se.llbit.chunky.renderer.scene.AsynchronousSceneManager.run(AsynchronousSceneManager.java:81)

**Comment by leMaik** [comment]
@aBitterMelon This should be fixed in the next snapshot (I just triggered a rebuild, should be up in a few minutes). Please re-open this issue if it isn't fixed
