### ISSUE TITLE
Cannot find JavaFX

### ISSUE THREAD

**Issue by orangemn6** [chunky-dev/chunky#925]
Hello, I am on Arch linux and when trying to run chunky, I get the following error:

```java
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/Stage
	at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:315)
	at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:223)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Stage
	... 2 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```
I am using [Liberica Full JDK](https://bell-sw.com/pages/downloads/#/java-8-lts)

**Comment by leMaik** [comment]
This is due to JavaFX not being installed or not being found. Is JavaFX included in Liberica Full JDK?

**Comment by orangemn6** [comment]
@leMaik I am pretty sure it is. I also tried updating alternatives for java with no luck

**Comment by NotStirred** [comment]
Just checked the source, doesn't look like it is

**Comment by orangemn6** [comment]
Hm ok. Can you guys suggest a java version that has it inbuilt? (preferably java 8)

**Comment by leMaik** [comment]
Oracle Java 8 has it built-in

**Comment by orangemn6** [comment]
I reinstalled oracle jre 8 and it worked! Thank you very much!

**Comment by leMaik** [comment]
Nice! Happy rendering, if you have further questions or want to show your renders, our discord server or subreddit are great places to do that. 😁
